services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-29T01-20-47Z
    command: server --console-address ":9001" /data
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.2
    # Extra dependencies are needed for remote tracking
    command: >
      bash -c "
        pip install uv
        uv pip install --system psycopg2-binary boto3
        mlflow server --host 0.0.0.0 --port 8080 --workers 1
      "
    ports:
      - "8080:8080"
    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.sqlite
      MLFLOW_ARTIFACTS_DESTINATION: s3://mlflow
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      MLFLOW_S3_IGNORE_TLS: "true"
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_ACCESS_KEY_ID: minioadmin
    depends_on:
      minio:
        condition: service_healthy
    # HACK: Gunicorn process is not PID 1 so service won't gracefully shutdown
    # https://stackoverflow.com/a/46237832
    stop_grace_period: 1s

  prefect:
    image: prefecthq/prefect:3.0.0rc10-python3.11
    command: >
      bash -c "
        prefect config set PREFECT_API_URL=http://0.0.0.0:4200/api
        prefect server start --host 0.0.0.0
      "
    ports:
      - "4200:4200"

  # NOTE: Some issues on ARM Macs
  ray-head:
    image: rayproject/ray:2.31.0-py311-cpu
    command: ray start --head --port 6379 --dashboard-host 0.0.0.0 --ray-client-server-port 10001 --block
    ports:
      - "10001:10001"
      - "6379:6379"
      - "8265:8265"

  ray-worker:
    image: rayproject/ray:2.31.0-py311-cpu
    command: ray start --address ray-head:6379 --block
    depends_on:
      ray-head:
        condition: service_started

volumes:
  minio-data:
    driver: local
    driver_opts:
      type: none
      device: ./minio-data
      o: bind
